# Chapter 5 The Basics of NumPy Arrays

## Numpy Array Attributes

In [2]:
import numpy as np
rng = np.random.default_rng(seed=1701) # seed for reproducibility

x1 = rng.integers(10, size=6) # one-dimensional array
x2 = rng.integers(10, size=(3, 4)) # two-dimensional array
x3 = rng.integers(10, size=(3, 4, 5)) # three-dimensional array

In [7]:
print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size:", x3.size)
print("dtype:", x3.dtype)

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60
dtype: int64


## Array Indexing: Accessing Single Elements

In [50]:
x1

array([3, 4, 0, 3, 8, 6])

In [51]:
x1[0]

3

In [52]:
x1[4]

8

In [53]:
# negative indices
x1[-1]

6

In [54]:
x1[-2]

8

In [55]:
# multidimensional array
x2

array([[12,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]])

In [56]:
x2[0, 0]

12

In [57]:
x2[2, 0]

0

In [58]:
x2[2, -1]

9

In [59]:
# modify elements
x2[0, 0] = 12
x2

array([[12,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]])

In [60]:
x1[0] = 3.14150 # this will be truncated!
x1

array([3, 4, 0, 3, 8, 6])

## Array Slicing: Access Subarrays

The NumPy slicing syntax follows that of the standard Ptyhon list;
to access a slice of an array x, use this

`x[start:stop:step]`

### One-Dimensional Subarrays

In [61]:
x1

array([3, 4, 0, 3, 8, 6])

In [62]:
x1[:3] # first three elements

array([3, 4, 0])

In [63]:
x1[3:] # elements after index 3

array([3, 8, 6])

In [64]:
x1[1:4] # middle subarray

array([4, 0, 3])

In [66]:
x1[::2] # every second element

array([3, 0, 8])

In [69]:
x1[1::2] # every second element, starting at index 1

array([4, 3, 6])

A potentially confusing case is when the step value is negattive.

In this case, the defaults for **start** and **stop** are swapped.

In [71]:
x1[::-1] # all elements, reversed

array([6, 8, 3, 0, 4, 3])

In [72]:
x1[4::-2] # every second element from index 4, reversed

array([8, 0, 3])

### Multidimensional Subarrays

In [73]:
x2

array([[12,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]])

In [75]:
x2[:2, :3] # first two rows & three columns

array([[12,  1,  3],
       [ 4,  0,  2]])

In [78]:
x2[:3, ::2] # three rows, every second column

array([[12,  3],
       [ 4,  2],
       [ 0,  6]])

In [80]:
x2[::-1, ::-1] # all rows & columns, reversed

array([[ 9,  6,  0,  0],
       [ 3,  2,  0,  4],
       [ 7,  3,  1, 12]])

One commonly needed routine is accessing single rows or columns of an array.

This can be done by combining indexing and slicing, using an empty slice maked by a sing colon `(:)`

In [82]:
x2[:, 0] # first column of x2

array([12,  4,  0])

In [83]:
x2[0, :] # first row of x2

array([12,  1,  3,  7])

In the case of **row** access, the empty slice can be omitted for a more compact syntax.

In [84]:
x2[0]

array([12,  1,  3,  7])

### Subarrays as No-Copy Views

In [85]:
print(x2)

[[12  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


In [87]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  1]
 [ 4  0]]


In [88]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  1]
 [ 4  0]]


In [89]:
print(x2)

[[99  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


### Creating Copies of Arrays

In [90]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  1]
 [ 4  0]]


In [91]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  1]
 [ 4  0]]


In [92]:
print(x2)

[[99  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


## Reshaping of Arrays

In [94]:
grid = np.arange(1, 10).reshape(3, 3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [98]:
x = np.array([1, 2, 3])
x.reshape((1, 3)) # row vector via reshape

array([[1, 2, 3]])

In [101]:
x.reshape((3, 1)) # column vector via reshape

array([[1],
       [2],
       [3]])

A convenient shorthand for this is to use np.newaxis in the slicing syntax

In [103]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [106]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

## Array Concatenation and Splitting

### Concatenation of Arrays

In [107]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [110]:
# concatenate more than two arrays at once
z = np.array([99, 99, 99])
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [111]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [112]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [113]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

For working with arrays of mixed dimensions, it can be clearer to use the

**np.vstack** (vertical stack) and **np.hstack** (horizontal stack) functions.

In [114]:
# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [115]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

### Splitting of Arrays

In [116]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [117]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [119]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [121]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
